export { default as AboutUs} from './aboutUs/AboutUs'
export { default as Design} from './design/Design'
export { default as Footer} from './footer/Footer'
export { default as Header} from './header/Header'
export { default as Navbar} from './navbar/Navbar'
export { default as Services} from './services/Services'
export { default as Team} from './team/Team'